### ISSUE TITLE
Dump commands do not produce valid yaml documents

### ISSUE THREAD

**Issue by justaugustus** [uwu-tools/peribolos#78]
Running a dump yields the following:

```console
go run main.go --dump uwu-tools --github-token-path ~/.github-token | tee uwu-tools.yaml
```

```json
{"client":"github","component":"unset","file":"/Users/augustus/go/pkg/mod/k8s.io/test-infra@v0.0.0-20220701081723-ad3e4ab74c32/prow/github/client.go:910","func":"k8s.io/test-infra/prow/github.(*client).log","level":"info","msg":"Throttle(300, 100, *)","severity":"info","time":"2022-07-06T07:24:29-04:00"}
{"client":"github","component":"unset","file":"/Users/augustus/go/pkg/mod/k8s.io/test-infra@v0.0.0-20220701081723-ad3e4ab74c32/prow/github/client.go:910","func":"k8s.io/test-infra/prow/github.(*client).log","level":"info","msg":"GetOrg(uwu-tools)","severity":"info","time":"2022-07-06T07:24:29-04:00"}
{"client":"github","component":"unset","file":"/Users/augustus/go/pkg/mod/k8s.io/test-infra@v0.0.0-20220701081723-ad3e4ab74c32/prow/github/client.go:910","func":"k8s.io/test-infra/prow/github.(*client).log","level":"info","msg":"User()","severity":"info","time":"2022-07-06T07:24:29-04:00"}
{"client":"github","component":"unset","file":"/Users/augustus/go/pkg/mod/k8s.io/test-infra@v0.0.0-20220701081723-ad3e4ab74c32/prow/github/client.go:910","func":"k8s.io/test-infra/prow/github.(*client).log","level":"info","msg":"ListOrgMembers(uwu-tools, admin)","severity":"info","time":"2022-07-06T07:24:30-04:00"}
{"client":"github","component":"unset","file":"/Users/augustus/go/pkg/mod/k8s.io/test-infra@v0.0.0-20220701081723-ad3e4ab74c32/prow/github/client.go:910","func":"k8s.io/test-infra/prow/github.(*client).log","level":"info","msg":"ListOrgMembers(uwu-tools, member)","severity":"info","time":"2022-07-06T07:24:30-04:00"}
{"client":"github","component":"unset","file":"/Users/augustus/go/pkg/mod/k8s.io/test-infra@v0.0.0-20220701081723-ad3e4ab74c32/prow/github/client.go:910","func":"k8s.io/test-infra/prow/github.(*client).log","level":"info","msg":"ListTeams(uwu-tools)","severity":"info","time":"2022-07-06T07:24:30-04:00"}
{"client":"github","component":"unset","file":"/Users/augustus/go/pkg/mod/k8s.io/test-infra@v0.0.0-20220701081723-ad3e4ab74c32/prow/github/client.go:910","func":"k8s.io/test-infra/prow/github.(*client).log","level":"info","msg":"GetRepos(uwu-tools, false)","severity":"info","time":"2022-07-06T07:24:30-04:00"}
{"client":"github","component":"unset","file":"/Users/augustus/go/pkg/mod/k8s.io/test-infra@v0.0.0-20220701081723-ad3e4ab74c32/prow/github/client.go:910","func":"k8s.io/test-infra/prow/github.(*client).log","level":"info","msg":"GetRepo(uwu-tools, go-ghcrawl)","severity":"info","time":"2022-07-06T07:24:30-04:00"}
{"component":"unset","file":"/Users/augustus/prj/relengfam/peribolos/cmd/main.go:84","func":"github.com/relengfam/peribolos/cmd.rootCmd","level":"info","msg":"Dumping orgs[\"uwu-tools\"]:","severity":"info","time":"2022-07-06T07:24:30-04:00"}
```

```yaml
admins:
- auggie-bot
- justaugustus
- sethmccombs
billing_email: ***@example.com
company: ""
default_repository_permission: read
description: ""
email: ""
has_organization_projects: true
has_repository_projects: true
location: ""
members_can_create_repositories: true
name: ""
repos:
  go-ghcrawl:
    default_branch: main
    has_projects: true
```

---

Now, let's try a `merge`:

```console
./admin/update.sh --github-token-path ~/.github-token
```

```console
+++ dirname ./admin/update.sh
++ cd ./admin/..
++ pwd -P
+ REPO_ROOT=/Users/augustus/prj/relengfam/peribolos
+ readonly REPO_ROOT
+ admins=('cpanato' 'justaugustus')
+ readonly admins
+ cd /Users/augustus/prj/relengfam/peribolos
+ make update-prep
cat: imagerefs: No such file or directory
make: Circular merge <- merge dependency dropped.
mkdir -p "/Users/augustus/prj/relengfam/peribolos/_output"
/Users/augustus/prj/relengfam/peribolos/_output/bin/peribolos merge \
		--merge-teams \
		--org-part=uwu-tools=config/uwu-tools/org.yaml \
		> /Users/augustus/prj/relengfam/peribolos/_output/gen-config.yaml
+ cmd=/Users/augustus/prj/relengfam/peribolos/_output/bin/peribolos
+ args=(--config-path="${REPO_ROOT}/_output/gen-config.yaml" --fix-org --fix-org-members --fix-teams --fix-team-members "${admins[@]/#/--required-admins=}")
+ /Users/augustus/prj/relengfam/peribolos/_output/bin/peribolos --config-path=/Users/augustus/prj/relengfam/peribolos/_output/gen-config.yaml --fix-org --fix-org-members --fix-teams --fix-team-members --required-admins=cpanato --required-admins=justaugustus --github-token-path /Users/augustus/.github-token
{}
```

```json
{"client":"github","component":"unset","file":"/Users/augustus/go/pkg/mod/k8s.io/test-infra@v0.0.0-20211221011455-3d87616db8ae/prow/github/client.go:889","func":"k8s.io/test-infra/prow/github.(*client).log","level":"info","msg":"Throttle(300, 100, *)","severity":"info","time":"2022-07-06T07:35:05-04:00"}
{"component":"unset","file":"/Users/augustus/prj/relengfam/peribolos/cmd/main.go:106","func":"github.com/relengfam/peribolos/cmd.rootCmd","level":"info","msg":"Finished syncing configuration.","severity":"info","time":"2022-07-06T07:35:05-04:00"}
```

Let's look at the output:

```console
❯ cat _output/gen-config.yaml
```

_output/gen-config.yaml:

```yaml
{}

orgs:
  uwu-tools:
    admins:
    - auggie-bot
    - cpanato
    - justaugustus
    - sethmccombs
    billing_email: ***@example.com
    company: ""
    default_repository_permission: read
    description: ""
    email: ""
    has_organization_projects: true
    has_repository_projects: true
    location: ""
    members_can_create_repositories: true
    name: ""
    repos:
      go-ghcrawl:
        default_branch: main
        has_projects: true
```

The above file is not a valid yaml document.

Note the following at the top of the file:

```yaml
{}

```

Note the same when using the `--help` flag:

```console
./admin/update.sh --github-token-path ~/.github-token --help
+++ dirname ./admin/update.sh
++ cd ./admin/..
++ pwd -P
+ REPO_ROOT=/Users/augustus/prj/relengfam/peribolos
+ readonly REPO_ROOT
+ admins=('cpanato' 'justaugustus')
+ readonly admins
+ cd /Users/augustus/prj/relengfam/peribolos
+ make update-prep
cat: imagerefs: No such file or directory
make: Circular merge <- merge dependency dropped.
mkdir -p "/Users/augustus/prj/relengfam/peribolos/_output"
/Users/augustus/prj/relengfam/peribolos/_output/bin/peribolos merge \
		--merge-teams \
		--org-part=uwu-tools=config/uwu-tools/org.yaml \
		> /Users/augustus/prj/relengfam/peribolos/_output/gen-config.yaml
+ cmd=/Users/augustus/prj/relengfam/peribolos/_output/bin/peribolos
+ args=(--config-path="${REPO_ROOT}/_output/gen-config.yaml" --fix-org --fix-org-members --fix-teams --fix-team-members "${admins[@]/#/--required-admins=}")
+ /Users/augustus/prj/relengfam/peribolos/_output/bin/peribolos --config-path=/Users/augustus/prj/relengfam/peribolos/_output/gen-config.yaml --fix-org --fix-org-members --fix-teams --fix-team-members --required-admins=cpanato --required-admins=justaugustus --github-token-path /Users/augustus/.github-token --help
{}

Usage:
   [flags]
   [command]

Available Commands:
  completion  Generate the autocompletion script for the specified shell
  help        Help about any command
  merge
  version     Prints the version

Flags:
      --allow-repo-archival                      If set, archiving repos is allowed while updating repos
      --allow-repo-publish                       If set, making private repos public is allowed while updating repos
      --config-path string                       Path to org config.yaml
      --confirm                                  Mutate github if set

<snip>

Use " [command] --help" for more information about a command.
```
